CREATE TABLE IF NOT EXISTS `wrong_question` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT 'student user id',
  `question_id` bigint NOT NULL COMMENT 'task/question id',
  `exam_id` bigint DEFAULT NULL COMMENT 'source exam id',
  `paper_name` varchar(255) DEFAULT NULL COMMENT 'paper name',
  `question` text COMMENT 'question stem snapshot',
  `category` varchar(64) DEFAULT NULL COMMENT 'question category',
  `choice` json DEFAULT NULL COMMENT 'choice options snapshot',
  `correct_answer` text COMMENT 'correct answer snapshot',
  `parse` text COMMENT 'analysis snapshot',
  `score` int DEFAULT NULL COMMENT 'question score',
  `type` varchar(64) DEFAULT NULL COMMENT 'difficulty tag',
  `knowledge_point` varchar(255) DEFAULT NULL COMMENT 'knowledge point',
  `wrong_count` int NOT NULL DEFAULT 0 COMMENT 'wrong times',
  `correct_streak` int NOT NULL DEFAULT 0 COMMENT 'continuous correct times',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT 'active/mastered/pending_manual',
  `last_user_answer` text COMMENT 'last user answer',
  `first_wrong_time` datetime DEFAULT NULL,
  `last_wrong_time` datetime DEFAULT NULL,
  `last_practice_time` datetime DEFAULT NULL,
  `create_by` varchar(255) DEFAULT NULL,
  `update_by` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del` tinyint DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wrong_user_question` (`user_id`, `question_id`),
  KEY `idx_wrong_user_status` (`user_id`, `status`),
  KEY `idx_wrong_last_time` (`last_wrong_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='student wrong question book';
